version: "3.8"
services:
  api:
    container_name: api-container
    image: node:18
    working_dir: /usr/src/typescript-project-seed
    restart: always
    volumes:
      - ./dist/:/usr/src/typescript-project-seed/dist/
      - ./package.json:/usr/src/typescript-project-seed/package.json
    command: bash -c "npm install --omit=dev && npm start"
    ports: 
      - "5050:5050"