name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [master, development]

jobs:
  test-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: goomer-lista-rango-test
        ports: 
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: 'Create env file'
      run: |
          touch .env
          echo DATABASE_URL_TEST="postgres://postgres:admin@localhost:5432/goomer-lista-rango-test" >> .env
    - run: npm install
    - run: npm run test:server

  deploy-test:
    needs: test-ci
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    concurrency: deploy-to-test
    environment: test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: echo "Deploy"

  deploy-production:
    needs: test-ci
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: echo "Deploy"
